### ISSUE TITLE
Have you tried to add more FAM module to improve detection performance like cascade faster rcnn?Thank you!

### ISSUE THREAD

**Issue by LoveDLWujing** [csuhan/s2anet#32]

**Comment by csuhan** [comment]
We have not tested it for the speed-accuracy trade-off: bbox encoding and decoding are time consuming.
But you can validate it by applying AlignConv multiple times and feed the output of prev FAM to the next one.
We think the result will be promising.

**Comment by LoveDLWujing** [comment]
I have implemented the cascade FAM module such as 2 FAM Module.
But i wonder which is better for the input feature of the Second FAM module, the input x or Align_feat from first FAM module? 
Can u give me some advice? 
Thanks!

**Comment by csuhan** [comment]
1. Both `x` and `aligned_feat` are interpretable, but may differ in the receptive field. If you choose `x` as the input, then cascade FAM becomes cascade ARN. So in this way, `aligned feat` may be better.
2. Our experiments show that 0.5-0.4 is fine for both FAM and ODM. You can also try the cascade R-CNN style: 0.5-0.4, 0.6-0.5, 0.7-0.6.

**Comment by yzk-lab** [comment]
> I have implemented the cascade FAM module such as 2 FAM Module.
> But i wonder which is better for the input feature of the Second FAM module, the input x or Align_feat from the first FAM module?
> And how to set the iou threshold of positive anchor for each FAM module?
> Can u give me some advices?
> Thanks!

how to cascade the FAM? can you give me some advuces?thanks.

**Comment by csuhan** [comment]
Hi, @yzk-lab , we have implemented a cascade version, see [cascade_s2anet_2s_r50_fpn_3x_hrsc2016.py](https://github.com/csuhan/s2anet/blob/master/configs/hrsc2016/cascade_s2anet_2s_r50_fpn_3x_hrsc2016.py) for an example.

**Comment by yzk-lab** [comment]
thanks for your reply.it seems helpful for me! but&nbsp; i still have some doubts.
1.your repo said that the first stage use ACL(alignment conv layer) to align the feature before the reg and cls,how we get the offset&nbsp; to align the feature?
2.wether the number of cascade stages can be changed in the configs?i can not touch the parameter of the cascade stages.
3.does the cascade suitable for the DOTA/resnet101-rotated?
hope for your reply!thank you!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "csuhan"<notifications@github.com&gt;; 
发送时间: 2021年1月5日(星期二) 晚上10:49
收件人: "csuhan/s2anet"<s2anet@noreply.github.com&gt;; 
抄送: "追梦"<1195803471@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [csuhan/s2anet] Have you tried to add more FAM module to improve detection performance like cascade faster rcnn?Thank you! (#32)





 
Hi, @yzk-lab , we have implemented a cascade version, see cascade_s2anet_2s_r50_fpn_3x_hrsc2016.py for an example.

**Comment by csuhan** [comment]
1. The offset fileds are transformed from the predefined anchors.
2. Yes. See cascade_s2anet_1s and cascade_s2anet_1s for a example.
3. Yes.
